### ISSUE TITLE
bug when using scale on MemoryAddress

### ISSUE THREAD

**Issue by rqndom** [jbremer/pyasm2#5]
This code works:

```python
mov(eax, [ebx+0x4])
```
`>>> mov eax, [ebx+0x4]`

But this one outputs an error:

```python
mov(eax, [ebx*4+0x4])
```
 `>>> <repr(<pyasm2.x86.mov at 0x7f59dd3af320>) failed: AttributeError: 'int' object has no attribute 'value'>`

It appears to be related to the `disp` attribute.

Proposed patch:
```diff
--- x86.py.bak	2016-10-14 01:06:35.613063043 +0200
+++ x86.py	2016-10-14 01:04:42.665010353 +0200
@@ -283,7 +283,7 @@
             q = str(self.reg2) if self.mult == 1 else \
                 str(self.reg2) + '*' + str(self.mult)
             s += q if not len(s) else '+' + q
-        if self.disp.value:
+        if self.disp:
             if self.disp >= 0:
                 q = '0x%x' % int(self.disp)
             else:
```

**Comment by jbremer** [comment]
Looks fine to me, give me a minute. Do note that `pyasm2` is no longer maintained ;-)

**Comment by rqndom** [comment]
Ok with maintenance, I will make a fork to work on my side (I see other little modifications).
If you are interested, I could then send you merge requests.
Thank you for your feedback :)
